spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.1:5432/find_your_pet
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql

firebase:
  type: service_account
  project_id: ${FIREBASE_PROJECT_ID}
  private_key_id: ${FIREBASE_PRIVATE_KEY_ID}
  private_key: ${FIREBASE_PRIVATE_KEY}
  client_email: ${FIREBASE_CLIENT_EMAIL}
  client_id: ${FIREBASE_CLIENT_ID}
  token_uri: https://oauth2.googleapis.com/token

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}
