spring:
  application:
    name: FindYourPet
  # Database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/find_your_pet}
    username: ${POSTGRES_USER:pet_admin}
    password: ${POSTGRES_PASSWORD:pet_admin}
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql

firebase:
  type: service_account
  project_id: ${FIREBASE_PROJECT_ID}
  private_key_id: ${FIREBASE_PRIVATE_KEY_ID}
  private_key: ${FIREBASE_PRIVATE_KEY}
  client_email: ${FIREBASE_CLIENT_EMAIL}
  client_id: ${FIREBASE_CLIENT_ID}
  token_uri: https://oauth2.googleapis.com/token

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}
